"""Initial migration: create users, sessions, ha_instances, audit_logs tables

Revision ID: 7c29127e0f70
Revises: 
Create Date: 2026-01-25 03:46:49.462039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c29127e0f70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ha_instances_container_id', table_name='ha_instances')
    op.drop_index('ix_ha_instances_user_id', table_name='ha_instances')
    op.drop_table('ha_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ha_instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('container_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('host_port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('docker_network', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('internal_api_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('config_yaml', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ha_instances_pkey'),
    sa.UniqueConstraint('container_name', name='ha_instances_container_name_key'),
    sa.UniqueConstraint('host_port', name='ha_instances_host_port_key')
    )
    op.create_index('ix_ha_instances_user_id', 'ha_instances', ['user_id'], unique=False)
    op.create_index('ix_ha_instances_container_id', 'ha_instances', ['container_id'], unique=False)
    # ### end Alembic commands ###
